version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 9906:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1

volumes:
  wordpress:
  mariadb:
